package firewall

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"kiro_waf/internal/shared/config"
	"kiro_waf/internal/shared/storage"
)

type Options struct {
	CloudflareIPv4 []string
	CloudflareIPv6 []string
	Now            time.Time
}

type Plan struct {
	Ruleset string
	SHA256  string
}

type Snapshot struct {
	GeneratedAt string `json:"generated_at"`
	Mode        string `json:"mode"`
	SHA256      string `json:"sha256"`
	Ruleset     string `json:"ruleset"`
}

func GenerateNftables(runtime config.RuntimeConfig, opts Options) (Plan, error) {
	if !runtime.Firewall.Enabled {
		return Plan{}, errors.New("runtime firewall is disabled")
	}
	adminV4, adminV6, err := splitCIDRs(firstNonEmptySlice(runtime.Firewall.AdminCIDRs, runtime.AdminCIDRs))
	if err != nil {
		return Plan{}, err
	}
	if runtime.Firewall.SSHAdminOnly && len(adminV4)+len(adminV6) == 0 {
		return Plan{}, errors.New("admin CIDR allowlist is required when ssh_admin_only is true")
	}

	allowPorts, err := normalizePorts(runtime.Firewall.AllowPorts, runtime.SSHPort)
	if err != nil {
		return Plan{}, err
	}
	cfV4, cfV6, err := cloudflareRanges(runtime, opts)
	if err != nil {
		return Plan{}, err
	}

	var b strings.Builder
	writeLine(&b, "# generated by kiro_waf firewall dry-run")
	writeLine(&b, "# phase: dry-run only, no system changes applied")
	writeLine(&b, "flush table inet kiro_waf")
	writeLine(&b, "table inet kiro_waf {")
	writeSet(&b, "kiro_admin_v4", "ipv4_addr", adminV4)
	writeSet(&b, "kiro_admin_v6", "ipv6_addr", adminV6)
	writeSet(&b, "kiro_cloudflare_v4", "ipv4_addr", cfV4)
	writeSet(&b, "kiro_cloudflare_v6", "ipv6_addr", cfV6)
	writeDynamicSet(&b, "kiro_temp_ban_v4", "ipv4_addr", runtime.Firewall.TemporaryBlockSeconds)
	writeDynamicSet(&b, "kiro_temp_ban_v6", "ipv6_addr", runtime.Firewall.TemporaryBlockSeconds)
	writePreroutingChain(&b)
	writeInputChain(&b, runtime, allowPorts, adminV4, adminV6, cfV4, cfV6)
	writeLine(&b, "}")

	ruleset := b.String()
	sum := sha256.Sum256([]byte(ruleset))
	return Plan{Ruleset: ruleset, SHA256: hex.EncodeToString(sum[:])}, nil
}

func WriteLastGoodSnapshot(dir string, runtime config.RuntimeConfig, plan Plan, now time.Time) (string, error) {
	if strings.TrimSpace(dir) == "" {
		return "", errors.New("snapshot directory is required")
	}
	if now.IsZero() {
		now = time.Now().UTC()
	}
	path := filepath.Join(dir, "last-good-nftables.json")
	err := storage.WriteJSONAtomic(path, Snapshot{
		GeneratedAt: now.Format(time.RFC3339),
		Mode:        runtime.Mode,
		SHA256:      plan.SHA256,
		Ruleset:     plan.Ruleset,
	})
	if err != nil {
		return "", err
	}
	return path, nil
}

func cloudflareRanges(runtime config.RuntimeConfig, opts Options) ([]string, []string, error) {
	if !runtime.CFOriginLock.Enabled {
		return nil, nil, nil
	}
	v4 := append([]string(nil), opts.CloudflareIPv4...)
	v6 := append([]string(nil), opts.CloudflareIPv6...)
	var err error
	if len(v4) == 0 && runtime.CFOriginLock.IPv4File != "" {
		v4, err = readCIDRFile(runtime.CFOriginLock.IPv4File)
		if err != nil {
			return nil, nil, err
		}
	}
	if len(v6) == 0 && runtime.CFOriginLock.IPv6File != "" {
		v6, err = readCIDRFile(runtime.CFOriginLock.IPv6File)
		if err != nil {
			return nil, nil, err
		}
	}
	if runtime.CFOriginLock.BlockDirectOriginHTTP && len(v4)+len(v6) == 0 {
		return nil, nil, errors.New("cloudflare origin lock requires IPv4 or IPv6 ranges")
	}
	v4, v6, err = splitCIDRs(append(v4, v6...))
	if err != nil {
		return nil, nil, err
	}
	return v4, v6, nil
}

func writePreroutingChain(b *strings.Builder) {
	writeLine(b, "  chain prerouting {")
	writeLine(b, "    type filter hook prerouting priority raw; policy accept;")
	writeLine(b, "    ip saddr @kiro_temp_ban_v4 drop comment \"kiro_temp_ban_v4\"")
	writeLine(b, "    ip6 saddr @kiro_temp_ban_v6 drop comment \"kiro_temp_ban_v6\"")
	writeLine(b, "    tcp flags & (fin|syn|rst|ack) == 0x0 drop comment \"kiro_tcp_null_flags_drop\"")
	writeLine(b, "  }")
}

func writeInputChain(b *strings.Builder, runtime config.RuntimeConfig, allowPorts []int, adminV4 []string, adminV6 []string, cfV4 []string, cfV6 []string) {
	sshPort := runtime.SSHPort
	if sshPort == 0 {
		sshPort = 22
	}
	webPorts := intersectPorts(allowPorts, []int{80, 443})
	nonWebPorts := removePorts(allowPorts, 80, 443, sshPort)

	writeLine(b, "  chain input {")
	writeLine(b, "    type filter hook input priority filter; policy drop;")
	writeLine(b, "    iifname \"lo\" accept")
	writeLine(b, "    ct state established,related accept")
	writeLine(b, "    ip saddr @kiro_temp_ban_v4 drop comment \"kiro_input_temp_ban_v4\"")
	writeLine(b, "    ip6 saddr @kiro_temp_ban_v6 drop comment \"kiro_input_temp_ban_v6\"")
	if len(adminV4) > 0 {
		writeLine(b, fmt.Sprintf("    ip saddr @kiro_admin_v4 tcp dport %d accept comment \"kiro_admin_ssh_v4\"", sshPort))
	}
	if len(adminV6) > 0 {
		writeLine(b, fmt.Sprintf("    ip6 saddr @kiro_admin_v6 tcp dport %d accept comment \"kiro_admin_ssh_v6\"", sshPort))
	}
	if !runtime.Firewall.SSHAdminOnly && containsPort(allowPorts, sshPort) {
		writeLine(b, fmt.Sprintf("    tcp dport %d accept comment \"kiro_ssh_open\"", sshPort))
	}
	if runtime.CFOriginLock.Enabled && runtime.CFOriginLock.BlockDirectOriginHTTP && len(webPorts) > 0 {
		if len(cfV4) > 0 {
			writeLine(b, fmt.Sprintf("    ip saddr @kiro_cloudflare_v4 tcp dport %s accept comment \"kiro_cloudflare_origin_v4\"", nftPortSet(webPorts)))
		}
		if len(cfV6) > 0 {
			writeLine(b, fmt.Sprintf("    ip6 saddr @kiro_cloudflare_v6 tcp dport %s accept comment \"kiro_cloudflare_origin_v6\"", nftPortSet(webPorts)))
		}
		writeLine(b, fmt.Sprintf("    tcp dport %s drop comment \"kiro_cloudflare_direct_origin_drop\"", nftPortSet(webPorts)))
	} else if len(webPorts) > 0 {
		writeLine(b, fmt.Sprintf("    tcp dport %s accept comment \"kiro_web_ports\"", nftPortSet(webPorts)))
	}
	if len(nonWebPorts) > 0 {
		writeLine(b, fmt.Sprintf("    tcp dport %s accept comment \"kiro_allowed_tcp_ports\"", nftPortSet(nonWebPorts)))
	}
	writeLine(b, "    ip protocol icmp limit rate 10/second accept comment \"kiro_icmp_limited\"")
	writeLine(b, "    ip6 nexthdr icmpv6 limit rate 10/second accept comment \"kiro_icmpv6_limited\"")
	writeLine(b, "    counter drop comment \"kiro_default_drop\"")
	writeLine(b, "  }")
}

func writeSet(b *strings.Builder, name string, nftType string, elements []string) {
	writeLine(b, fmt.Sprintf("  set %s {", name))
	writeLine(b, fmt.Sprintf("    type %s;", nftType))
	writeLine(b, "    flags interval;")
	if len(elements) > 0 {
		writeLine(b, fmt.Sprintf("    elements = { %s }", strings.Join(elements, ", ")))
	}
	writeLine(b, "  }")
}

func writeDynamicSet(b *strings.Builder, name string, nftType string, timeoutSeconds int) {
	if timeoutSeconds <= 0 {
		timeoutSeconds = 900
	}
	writeLine(b, fmt.Sprintf("  set %s {", name))
	writeLine(b, fmt.Sprintf("    type %s;", nftType))
	writeLine(b, "    flags interval,timeout;")
	writeLine(b, fmt.Sprintf("    timeout %ds;", timeoutSeconds))
	writeLine(b, "  }")
}

func readCIDRFile(path string) ([]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cidrs []string
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		cidrs = append(cidrs, line)
	}
	return cidrs, nil
}

func splitCIDRs(values []string) ([]string, []string, error) {
	v4 := []string{}
	v6 := []string{}
	seen := map[string]bool{}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		ip, network, err := net.ParseCIDR(value)
		if err != nil {
			return nil, nil, fmt.Errorf("invalid CIDR %q: %w", value, err)
		}
		normalized := network.String()
		if seen[normalized] {
			continue
		}
		seen[normalized] = true
		if ip.To4() != nil {
			v4 = append(v4, normalized)
		} else {
			v6 = append(v6, normalized)
		}
	}
	sort.Strings(v4)
	sort.Strings(v6)
	return v4, v6, nil
}

func normalizePorts(values []int, sshPort int) ([]int, error) {
	if sshPort == 0 {
		sshPort = 22
	}
	ports := append([]int{sshPort}, values...)
	seen := map[int]bool{}
	out := []int{}
	for _, port := range ports {
		if port <= 0 || port > 65535 {
			return nil, fmt.Errorf("invalid port %d", port)
		}
		if seen[port] {
			continue
		}
		seen[port] = true
		out = append(out, port)
	}
	sort.Ints(out)
	return out, nil
}

func nftPortSet(ports []int) string {
	if len(ports) == 1 {
		return fmt.Sprintf("%d", ports[0])
	}
	parts := make([]string, 0, len(ports))
	for _, port := range ports {
		parts = append(parts, fmt.Sprintf("%d", port))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func writeLine(b *strings.Builder, line string) {
	b.WriteString(line)
	b.WriteByte('\n')
}

func firstNonEmptySlice(primary []string, fallback []string) []string {
	if len(primary) > 0 {
		return primary
	}
	return fallback
}

func intersectPorts(values []int, targets []int) []int {
	targetSet := map[int]bool{}
	for _, target := range targets {
		targetSet[target] = true
	}
	var out []int
	for _, value := range values {
		if targetSet[value] {
			out = append(out, value)
		}
	}
	return out
}

func removePorts(values []int, remove ...int) []int {
	removeSet := map[int]bool{}
	for _, value := range remove {
		removeSet[value] = true
	}
	var out []int
	for _, value := range values {
		if !removeSet[value] {
			out = append(out, value)
		}
	}
	return out
}

func containsPort(values []int, want int) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
