package proxy

import (
	"errors"
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"kiro_waf/internal/shared/config"
	"kiro_waf/internal/shared/storage"
)

type Plan struct {
	NginxConfig      string
	CloudflareRealIP string
	Warnings         []string
}

type ValidateRunner interface {
	Validate(configPath string) error
}

type NginxRunner struct {
	Binary string
}

func (r NginxRunner) Validate(configPath string) error {
	binary := r.Binary
	if binary == "" {
		binary = "nginx"
	}
	dir := filepath.Dir(configPath)
	cmd := exec.Command(binary, "-t", "-p", dir+string(os.PathSeparator), "-c", filepath.Base(configPath))
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("nginx -t failed: %w: %s", err, string(out))
	}
	return nil
}

func GenerateNginx(runtime config.RuntimeConfig) (Plan, error) {
	if runtime.Mode == "server" {
		return Plan{
			NginxConfig:      "# generated by kiro_waf proxy generator\n# proxy disabled in server mode\n",
			CloudflareRealIP: "# Cloudflare real IP disabled\n",
		}, nil
	}
	if len(runtime.Sites) == 0 {
		return Plan{}, errors.New("proxy generation requires at least one site")
	}
	pools := map[string]config.RuntimeBackendPool{}
	for _, pool := range runtime.BackendPools {
		pools[pool.ID] = pool
	}
	var b strings.Builder
	writeLine(&b, "# generated by kiro_waf proxy generator")
	writeLine(&b, "# phase: validate only, no nginx reload")
	writeLine(&b, "worker_processes auto;")
	writeLine(&b, "events { worker_connections 1024; }")
	writeLine(&b, "http {")
	writeLine(&b, "  proxy_cache_path /var/cache/nginx/kiro levels=1:2 keys_zone=kiro_cache:100m inactive=10m max_size=1g use_temp_path=off;")
	writeLine(&b, "  limit_req_zone $binary_remote_addr zone=kiro_ip_req:20m rate=2r/s;")
	writeLine(&b, "  limit_conn_zone $binary_remote_addr zone=kiro_ip_conn:20m;")
	writeLine(&b, "  include /etc/nginx/mime.types;")
	writeLine(&b, "  default_type application/octet-stream;")
	writeLine(&b, "")

	for _, pool := range sortedPools(runtime.BackendPools) {
		if err := writeUpstream(&b, pool); err != nil {
			return Plan{}, err
		}
	}
	warnings := []string{}
	for _, site := range sortedSites(runtime.Sites) {
		if _, ok := pools[site.DefaultBackendPool]; !ok {
			return Plan{}, fmt.Errorf("site %q references unknown backend pool %q", site.ID, site.DefaultBackendPool)
		}
		siteWarnings, err := writeServer(&b, site, pools, runtime.CFOriginLock.Enabled)
		if err != nil {
			return Plan{}, err
		}
		warnings = append(warnings, siteWarnings...)
	}
	writeLine(&b, "}")

	cf, err := generateCloudflareRealIP(runtime)
	if err != nil {
		return Plan{}, err
	}
	return Plan{NginxConfig: b.String(), CloudflareRealIP: cf, Warnings: warnings}, nil
}

func WritePlan(dir string, plan Plan) (string, string, error) {
	if strings.TrimSpace(dir) == "" {
		return "", "", errors.New("proxy output directory is required")
	}
	mainPath := filepath.Join(dir, "kiro-nginx.conf")
	cfPath := filepath.Join(dir, "cloudflare-real-ip.conf")
	if err := storage.WriteJSONAtomic(filepath.Join(dir, ".kiro-proxy-plan.json"), map[string]any{
		"nginx_config":       mainPath,
		"cloudflare_real_ip": cfPath,
		"warnings":           plan.Warnings,
	}); err != nil {
		return "", "", err
	}
	if err := os.WriteFile(mainPath, []byte(plan.NginxConfig), 0o644); err != nil {
		return "", "", err
	}
	if err := os.WriteFile(cfPath, []byte(plan.CloudflareRealIP), 0o644); err != nil {
		return "", "", err
	}
	return mainPath, cfPath, nil
}

func ValidatePlan(dir string, plan Plan, runner ValidateRunner) error {
	if runner == nil {
		return errors.New("nginx validation runner is required")
	}
	mainPath, _, err := WritePlan(dir, plan)
	if err != nil {
		return err
	}
	return runner.Validate(mainPath)
}

func writeUpstream(b *strings.Builder, pool config.RuntimeBackendPool) error {
	writeLine(b, fmt.Sprintf("  upstream %s {", nginxName(pool.ID)))
	for _, upstream := range sortedUpstreams(pool.Upstreams) {
		parsed, err := url.Parse(upstream.URL)
		if err != nil {
			return err
		}
		if parsed.Host == "" {
			return fmt.Errorf("upstream %q has empty host", upstream.ID)
		}
		writeLine(b, fmt.Sprintf("    server %s max_fails=3 fail_timeout=10s;", parsed.Host))
	}
	writeLine(b, "    keepalive 32;")
	writeLine(b, "  }")
	writeLine(b, "")
	return nil
}

func writeServer(b *strings.Builder, site config.RuntimeSite, pools map[string]config.RuntimeBackendPool, cloudflare bool) ([]string, error) {
	mode := firstNonEmpty(site.TLSMode, "flexible_http")
	if mode == "full_tls" {
		mode = "full_strict"
	}
	warnings := []string{}
	writeLine(b, "  server {")
	switch mode {
	case "flexible_http":
		writeLine(b, "    listen 80;")
	case "full_strict":
		if site.CertFile == "" || site.KeyFile == "" {
			return nil, fmt.Errorf("site %q full_strict requires certificate and private key", site.ID)
		}
		writeLine(b, "    listen 443 ssl;")
		writeLine(b, fmt.Sprintf("    ssl_certificate %s;", site.CertFile))
		writeLine(b, fmt.Sprintf("    ssl_certificate_key %s;", site.KeyFile))
		writeLine(b, "    ssl_protocols TLSv1.2 TLSv1.3;")
	default:
		return nil, fmt.Errorf("site %q has unsupported tls mode %q", site.ID, mode)
	}
	writeLine(b, fmt.Sprintf("    server_name %s;", strings.Join(site.Domains, " ")))
	if cloudflare {
		writeLine(b, "    include cloudflare-real-ip.conf;")
		writeLine(b, "    real_ip_header CF-Connecting-IP;")
	}
	writeLine(b, "    client_body_buffer_size 128k;")
	writeLine(b, "    client_max_body_size 10m;")
	writeLine(b, "    client_header_timeout 5s;")
	writeLine(b, "    client_body_timeout 10s;")
	writeLine(b, "    keepalive_timeout 15s;")
	writeLine(b, "    send_timeout 10s;")
	writeLine(b, "    limit_conn kiro_ip_conn 20;")
	writeLine(b, "    limit_req zone=kiro_ip_req burst=40 nodelay;")
	writeLine(b, "    if ($request_method ~* ^(TRACE|CONNECT)$) { return 405; }")
	writeLine(b, "    location ~* ^/(\\.env|\\.git|phpmyadmin|wp-login\\.php|xmlrpc\\.php) { return 444; }")
	writeLine(b, "    location ~* \\.(css|js|png|jpg|jpeg|gif|svg|webp|ico|woff|woff2)$ {")
	writeLine(b, "      proxy_cache kiro_cache;")
	writeLine(b, "      proxy_cache_valid 200 10m;")
	writeProxyHeaders(b)
	writeLine(b, fmt.Sprintf("      proxy_pass http://%s;", nginxName(site.DefaultBackendPool)))
	writeLine(b, "    }")

	for _, route := range sortedRoutes(site.Routes) {
		if route.Path == "/" {
			continue
		}
		if _, ok := pools[route.BackendPool]; !ok {
			return nil, fmt.Errorf("site %q route %q references unknown backend pool %q", site.ID, route.Path, route.BackendPool)
		}
		if mode == "flexible_http" && sensitiveRoute(route.Path) {
			warnings = append(warnings, fmt.Sprintf("site %s route %s uses flexible_http for sensitive path", site.ID, route.Path))
		}
		writeLocation(b, route)
	}
	rootPool := site.DefaultBackendPool
	for _, route := range site.Routes {
		if route.Path == "/" && route.BackendPool != "" {
			rootPool = route.BackendPool
		}
	}
	writeLocation(b, config.RuntimeRoute{Path: "/", BackendPool: rootPool})
	writeLine(b, "  }")
	writeLine(b, "")
	return warnings, nil
}

func writeLocation(b *strings.Builder, route config.RuntimeRoute) {
	writeLine(b, fmt.Sprintf("    location %s {", route.Path))
	if route.RPMPerIP > 0 {
		writeLine(b, fmt.Sprintf("      # kiro_route_rpm_per_ip %d", route.RPMPerIP))
		writeLine(b, "      limit_req zone=kiro_ip_req burst=20 nodelay;")
	}
	if route.MaxBodyMB > 0 {
		writeLine(b, fmt.Sprintf("      client_max_body_size %dm;", route.MaxBodyMB))
	}
	if route.CacheSeconds > 0 {
		writeLine(b, "      proxy_cache kiro_cache;")
		writeLine(b, fmt.Sprintf("      proxy_cache_valid 200 %ds;", route.CacheSeconds))
	}
	writeProxyHeaders(b)
	writeLine(b, fmt.Sprintf("      proxy_pass http://%s;", nginxName(route.BackendPool)))
	writeLine(b, "    }")
}

func writeProxyHeaders(b *strings.Builder) {
	writeLine(b, "      proxy_http_version 1.1;")
	writeLine(b, "      proxy_set_header Host $host;")
	writeLine(b, "      proxy_set_header X-Real-IP $remote_addr;")
	writeLine(b, "      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
	writeLine(b, "      proxy_set_header X-Forwarded-Proto $scheme;")
	writeLine(b, "      proxy_read_timeout 20s;")
	writeLine(b, "      proxy_connect_timeout 3s;")
	writeLine(b, "      proxy_send_timeout 10s;")
}

func generateCloudflareRealIP(runtime config.RuntimeConfig) (string, error) {
	if !runtime.CFOriginLock.Enabled {
		return "# Cloudflare real IP disabled\n", nil
	}
	var b strings.Builder
	writeLine(&b, "# generated by kiro_waf")
	for _, path := range []string{runtime.CFOriginLock.IPv4File, runtime.CFOriginLock.IPv6File} {
		if path == "" {
			continue
		}
		cidrs, err := readCIDRFile(path)
		if err != nil {
			return "", err
		}
		for _, cidr := range cidrs {
			writeLine(&b, fmt.Sprintf("set_real_ip_from %s;", cidr))
		}
	}
	writeLine(&b, "real_ip_header CF-Connecting-IP;")
	return b.String(), nil
}

func sortedPools(pools []config.RuntimeBackendPool) []config.RuntimeBackendPool {
	out := append([]config.RuntimeBackendPool(nil), pools...)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func sortedUpstreams(upstreams []config.RuntimeUpstream) []config.RuntimeUpstream {
	out := append([]config.RuntimeUpstream(nil), upstreams...)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func sortedSites(sites []config.RuntimeSite) []config.RuntimeSite {
	out := append([]config.RuntimeSite(nil), sites...)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func sortedRoutes(routes []config.RuntimeRoute) []config.RuntimeRoute {
	out := append([]config.RuntimeRoute(nil), routes...)
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Path == "/" {
			return false
		}
		if out[j].Path == "/" {
			return true
		}
		if len(out[i].Path) == len(out[j].Path) {
			return out[i].Path < out[j].Path
		}
		return len(out[i].Path) > len(out[j].Path)
	})
	return out
}

func nginxName(value string) string {
	replacer := strings.NewReplacer("-", "_", ".", "_")
	return replacer.Replace(value)
}

func sensitiveRoute(path string) bool {
	lower := strings.ToLower(path)
	return strings.Contains(lower, "login") || strings.Contains(lower, "admin") || strings.Contains(lower, "export")
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}

func writeLine(b *strings.Builder, line string) {
	b.WriteString(line)
	b.WriteByte('\n')
}

func readCIDRFile(path string) ([]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cidrs []string
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		cidrs = append(cidrs, line)
	}
	sort.Strings(cidrs)
	return cidrs, nil
}
